[database]
username = "postgres"
password = ""
host = "localhost"
port = 5432
dbname = "local_run"

[http]
expose = false
port = 8080

[security]
# Generate it with `openssl rand -base64 36`
jwt-secret = "your-very-secure-secret"
